// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfFbgTkPHEdzMS7jgK8Ro6kaL9mQh3Mo4',
    appId: '1:144845525749:web:0dc5f22aad2f4eed62ebbc',
    messagingSenderId: '144845525749',
    projectId: 'pashumitra-app-e9e4c',
    authDomain: 'pashumitra-app-e9e4c.firebaseapp.com',
    storageBucket: 'pashumitra-app-e9e4c.firebasestorage.app',
    measurementId: 'G-HQ2N3WLHFZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDv_VqUwQwS7s6f5bHfy0HKx13Ge_ZbP8',
    appId: '1:144845525749:android:7928a82661cb29ca62ebbc',
    messagingSenderId: '144845525749',
    projectId: 'pashumitra-app-e9e4c',
    storageBucket: 'pashumitra-app-e9e4c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-QO0WdjCG3F9chS6wnuls72ZrMV7Klko',
    appId: '1:144845525749:ios:51c22102ad5a0d4b62ebbc',
    messagingSenderId: '144845525749',
    projectId: 'pashumitra-app-e9e4c',
    storageBucket: 'pashumitra-app-e9e4c.firebasestorage.app',
    iosBundleId: 'com.example.pashumitraApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-QO0WdjCG3F9chS6wnuls72ZrMV7Klko',
    appId: '1:144845525749:ios:51c22102ad5a0d4b62ebbc',
    messagingSenderId: '144845525749',
    projectId: 'pashumitra-app-e9e4c',
    storageBucket: 'pashumitra-app-e9e4c.firebasestorage.app',
    iosBundleId: 'com.example.pashumitraApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfFbgTkPHEdzMS7jgK8Ro6kaL9mQh3Mo4',
    appId: '1:144845525749:web:5f883f9a0ed74e3562ebbc',
    messagingSenderId: '144845525749',
    projectId: 'pashumitra-app-e9e4c',
    authDomain: 'pashumitra-app-e9e4c.firebaseapp.com',
    storageBucket: 'pashumitra-app-e9e4c.firebasestorage.app',
    measurementId: 'G-ZJ5PJMS6NJ',
  );

}