// FILE: lib/main.dart

// ignore_for_file: use_build_context_synchronously
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:pashumitra_app/generated/app_localizations.dart';

import 'language_selection_screen.dart';
import 'onboarding_screen.dart';
import 'menu_page.dart';
import 'locale_provider.dart';
import 'theme_provider.dart';
import 'auth_provider.dart';

// 1. ADD FIREBASE IMPORTS
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // This file was just generated by the command


// A very simple main function to test if the app can run at all

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  // This checks if Firebase has already been initialized
  if (Firebase.apps.isEmpty) {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  }

  
  // Read all saved user settings before the app starts
  final prefs = await SharedPreferences.getInstance();
  final String? languageCode = prefs.getString('languageCode');
   final bool hasSeenOnboarding = prefs.getBool('hasSeenOnboarding') ?? false;
  final bool isDarkMode = prefs.getBool('isDarkMode') ?? false;
  final bool isLoggedIn = prefs.getBool('isLoggedIn') ?? false;

   Widget initialScreen;
  if (languageCode == null) {
    initialScreen = const LanguageSelectionScreen();
  } else if (!hasSeenOnboarding) {
    initialScreen = const OnboardingScreen();
  } else {
    initialScreen = const MainScreen();
  }

  runApp(MyApp(
    initialLocale: languageCode != null ? Locale(languageCode) : const Locale('en'),
    initialTheme: isDarkMode ? ThemeMode.dark : ThemeMode.light,
    isLoggedIn: isLoggedIn,
    initialScreen:initialScreen,
  ));
}

class MyApp extends StatelessWidget {
  final Locale initialLocale;
  final ThemeMode initialTheme;
  final bool isLoggedIn;
  final Widget initialScreen;

  const MyApp({
    super.key,
    required this.initialLocale,
    required this.initialTheme,
    required this.isLoggedIn, 
    required this.initialScreen,
  });

  @override
  Widget build(BuildContext context) {
    // MultiProvider makes all your app-wide states (language, theme, login)
    // available to all widgets below it.
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => LocaleProvider(initialLocale)),
        ChangeNotifierProvider(create: (_) => ThemeProvider(initialTheme)),
        ChangeNotifierProvider(create: (_) => AuthProvider(isLoggedIn)),
      ],
      child: Consumer<ThemeProvider>(
        builder: (context, themeProvider, child) {
          return MaterialApp(
            debugShowCheckedModeBanner: false,
            title: 'Pashumitra',
            // Theme settings for light and dark mode
            theme: ThemeData.light(), // Your light theme data
            darkTheme: ThemeData.dark(), // Your dark theme data
            themeMode: themeProvider.themeMode,
            
            // Localization settings
            locale: Provider.of<LocaleProvider>(context).locale,
            localizationsDelegates: const [
              AppLocalizations.delegate,
              GlobalMaterialLocalizations.delegate,
              GlobalWidgetsLocalizations.delegate,
              GlobalCupertinoLocalizations.delegate,
            ],
            supportedLocales: AppLocalizations.supportedLocales,
            
            // The app's home is ALWAYS the SplashScreen
            home: const SplashScreen(),
          );
        },
      ),
    );
  }
}

// Your SplashScreen now contains all the navigation logic
class SplashScreen extends StatefulWidget {
  const SplashScreen({super.key});

  @override
  State<SplashScreen> createState() => _SplashScreenState();
}

class _SplashScreenState extends State<SplashScreen>
    with SingleTickerProviderStateMixin {
  late AnimationController _controller;
  late Animation<double> _fadeAnimation;

  @override
  void initState() {
    super.initState();
    _controller =
        AnimationController(vsync: this, duration: const Duration(seconds: 2));
    _fadeAnimation = Tween<double>(begin: 0.0, end: 1.0).animate(
      CurvedAnimation(parent: _controller, curve: Curves.easeIn),
    );

    _controller.forward(); // start fade-in

    _navigateAfterSplash();
  }

  Future<void> _navigateAfterSplash() async {
    // Wait for the splash screen animation
    await Future.delayed(const Duration(seconds: 3));

    if (!mounted) return;

    // The logic to decide the next screen remains here
    final prefs = await SharedPreferences.getInstance();
    final String? languageCode = prefs.getString('languageCode');
    final bool hasSeenOnboarding = prefs.getBool('hasSeenOnboarding') ?? false;

    Widget destinationPage;

    if (languageCode == null) {
      destinationPage = const LanguageSelectionScreen();
    } else if (!hasSeenOnboarding) {
      destinationPage = const OnboardingScreen();
    } else {
      destinationPage = const MainScreen();
    }

    Navigator.pushReplacement(
      context,
      MaterialPageRoute(builder: (context) => destinationPage),
    );
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        decoration: const BoxDecoration(
          gradient: LinearGradient(
            colors: [Color(0xFF87CEEB), Colors.white],
            begin: Alignment.topCenter,
            end: Alignment.bottomCenter,
          ),
        ),
        child: Center(
          child: FadeTransition(
            opacity: _fadeAnimation,
            child: ClipRRect(
              borderRadius: BorderRadius.circular(35),
              child: Image.asset(
                'assets/images/pashimitra_logo.png',
                width: 220,
              ),
            ),
          ),
        ),
      ),
    );
  }
}